// Local names missing from the locale-codes library
export const localNames = {
  'ab': 'Аԥсшәа',
  'ace': 'bahsa Acèh',
  'acm': 'لهجة عراقية',
  'alt': 'алтайдыҥ тил',
  'an': 'aragonés',
  'ang': 'Ænglisc sprǣc',
  'arc': 'ܠܫܢܐ ܐܪܡܝܐ',
  'arn': 'mapudungun',
  'ary': 'الداريجة',
  'arz': 'للغه المصريه الحديثه',
  'ast': 'asturianu',
  'atj': 'Atikamekw Nehiromowin',
  'av': 'авар мацI',
  'avk': 'Kotava',
  'awa': 'अवधी',
  'ay': 'Aymar aru',
  'az': 'Azərbaycan dili',
  'azb': 'تورك ديلی',
  'ban': 'Basa Bali',
  'bar': 'Boarisch',
  'bcl': 'Bikol',
  'bho': 'भोजपुरी',
  'bi': 'Bislama',
  'bjn': 'bahasa Banjar',
  'bm': 'Bamanankan',
  'bn': 'বাংলা',
  'bo': 'བོད་ཡིག',
  'bs': 'bosanski',
  'bxr': 'буряад хэлэн',
  'cdo': 'Mìng-dĕ̤ng-ngṳ̄',
  'ce': 'Noxçiyn mott',
  'ceb': 'Sinugboanon',
  'cho': 'Chahta',
  'chr': 'ᏣᎳᎩ ᎧᏬᏂᎯᏍᏗ',
  'chy': 'Tsêhesenêstsestôtse',
  'ckb': 'کوردیی ناوەندی',
  'cr': 'nēhiyawēwin',
  'crh': 'Qırım tili',
  'cs': 'čeština',
  'csb': 'Kaszëbsczi jãzëk',
  'cv': 'Чăваш чĕлхи',
  'cy': 'Cymraeg',
  'dag': 'Dagbanli',
  'de': 'Deutsch',
  'din': 'Thuɔŋjäŋ',
  'diq': 'Zazaki',
  'dsb': 'dolnoserbšćina',
  'dty': 'डोटेली',
  'el': 'ελληνικά',  
  'eml': 'Langua emiglièna-rumagnôla',
  'eu': 'Euskara',
  'ext': 'Lengua estremeña',
  'fa': 'فارسی',
  'fil': 'Wikang Filipino',
  'fj': 'vosa Vakaviti',
  'fon': 'fɔ̀ngbè',
  'frp': 'arpetan',
  'fr': 'français',
  'frr': 'Nuurdfresk',
  'fur': 'furlan',
  'fy': 'Frysk',
  'gag': 'Gagauz dili',
  'gan': '贛語',
  'glk': 'گيلکي',
  'grc': 'Ἀρχαία Ἑλληνική',
  'gsw': 'Elsässisch',
  'guc': 'Wayuunaiki',
  'ha': 'Hausa',
  'hak': 'Hak-kâ-ngî',
  'haw': 'ʻōlelo Hawaiʻi',
  'hsb': 'Hornjoserbšćina',
  'ht': 'Kreyòl ayisyen',
  'hy': 'հայերեն',
  'hyw': 'արեւմտահայերէն',
  'ia': 'Interlingua',
  'iba': 'jaku Iban',
  'ie': 'Interlingue',
  'ik': 'Iñupiatun',
  'ilo': 'Ilokano',
  'inh': 'гӏалгӏай',
  'io': 'Ido',
  'is': 'íslenska',
  'iu': 'ᐃᓄᒃᑎᑐᑦ',
  'jbo': 'la .lojban.',
  'ka': 'ქართული ენა',
  'kaa': 'Qaraqalpaq tili',
  'kab': 'taqbaylit',
  'kbd': 'Къэбэрдей',
  'kbp': 'Kabɩyɛ',
  'kg': 'kikongo',
  'kk-arab': 'قازاق ٴتىلى',
  'kk-cyrl': 'қазақ тілі',
  'kk-latn': 'Qazaq tılı',
  'km': 'ខ្មែរ',
  'knc': 'Yerwá Kànùrí',
  'koi': 'коми-пермяцкӧй кыв',
  'krc': 'Таулу тил',
  'ku': 'Zimanê Kurdî',
  'ku-arab': 'کوردی',
  'ku-latn': 'Kurdî',
  'kv': 'Коми кыв',
  'la': 'Lingua latina',
  'lad': 'Ladino',
  'lbe': 'лакку',
  'lez': 'лезги',
  'lfn': 'elefen',
  'li': 'Limburgs',
  'lij': 'Lengoa ligure',
  'lld': 'ladin',
  'ltg': 'Latgališu',
  'lzh': '文言文',
  'mai': 'मैथिली',
  'mdf': 'Мокшень кяль',
  'mg': 'Fiteny malagasy',
  'mhr': 'олык марий',
  'mi': 'Māori',
  'min': 'bahaso Minangkabau',
  'mk': 'македонски',
  'mn': 'монгол хэл',
  'mnc': 'ᠮᠠᠨᠵᡠ ᡤᡳᠰᡠᠨ',
  'mni': 'ꯃꯤꯇꯩ ꯂꯣꯟ',
  'mnw': 'ဘာသာမန်',
  'mos': 'mòoré',
  'mrj': 'Мары йӹлмӹ',
  'ms': 'Bahasa Melayu',
  'mwl': 'Mirandés',
  'my': 'မြန်မာဘာသာစကား',
  'myv': 'Эрзянь кель',
  'mzn': 'مازرونی زبون',
  'nah': 'Nawatlahtolli',
  'nan': 'Bân-lâm-gú',
  'nan-hani': '閩南語',
  'nap': 'Lengua napulitana',
  'nds': 'Plattdütsch',
  'nds-nl': 'Nederlaands Leegsaksies',
  'new': 'नेवाः भाय्',
  'nl': 'Nederlands',
  'nn': 'nynorsk',
  'no': 'norsk',
  'nov': 'Novial',
  'nrm': 'Normaund',
  'nso': 'Sepedi',
  'nv': 'Diné bizaad',
  'oc': 'lenga d\'òc',
  'oj': 'Anishinaabemowin',
  'olo': 'Livvinkarjala',
  'or': 'ଓଡ଼ିଆ ଭାଷା',
  'pam': 'Kapampángan',
  'pap': 'Papiamentu',
  'pap-aw': 'Papiamento',
  'pcd': 'picard',
  'pdc': 'Pennsylvanisch Deitsch',
  'pfl': 'Pälzisch',
  'pms': 'Piemontèis',
  'pnb': 'شاہ مُکھی',
  'pnt': 'ποντιακά',
  'qu': 'Qhichwa simi',
  'rgn': 'Rumagnol',
  'ro': 'limba română',
  'rsk': 'руски язик',
  'rue': 'русиньскый язык',
  'sah': 'Саха тыла',
  'sat': 'ᱥᱟᱱᱛᱟᱲᱤ',
  'sc': 'sardu',
  'sco': 'Scots',
  'scn': 'Sicilianu',
  'se': 'davvisámegiella',
  'sgs': 'Žemaitiu ruoda',
  'sh': 'srpskohrvatski jezik',
  'shi': 'Taclḥit',
  'shn': 'လိၵ်ႈတႆး',
  'sjd': 'кӣлтса̄мь кӣлл',
  'sje': 'bidumsámegiella',
  'sk': 'slovenčina',
  'sma': 'åarjelsaemiengïele',
  'smj': 'julevsámegiella',
  'smn': 'anarâškielâ',
  'sms': 'nuõʹrttsääʹmǩiõll',
  'sq': 'shqip',
  'sr': 'srpski',
  'src': 'српски',
  'stq': 'Seeltersk',
  'su': 'Basa Sunda',
  'sw': 'Kiswahili',
  'syl': 'ꠍꠤꠟꠐꠤ ꠝꠣꠔ',
  'szy': 'Sakizaya',
  'tcy': 'ತುಳು',
  'tg': 'забони тоҷикӣ',
  'tl': 'wikang Tagalog',
  'tly': 'Tolyšə zyvon',
  'to': 'Lea fakatonga',
  'tok': 'toki pona',
  'tum': 'Chitumbuka',
  'tyv': 'Тыва дыл',
  'udm': 'Удмурт кыл',
  'uz': 'Oʻzbek tili',
  'vec': 'Vèneto',
  'vep': 'vepsän kel\'',
  'vls': 'West-Vlams',
  'vro': 'võro kiil',
  'wa': 'walon',
  'war': 'Waray',
  'wuu': '吴语',
  'xal': 'Хальмг кел',
  'xmf': 'მარგალური ნინა',
  'yi': 'יידיש',
  'yua': 'mayaʼ tʼaan',
  'yue': '粵語',
  'za': 'Vahcuengh',
  'zea': 'Zeêuws',
  'zh': '中文',
  'zh-cn': '汉语',
  'zh-hans': '汉语',
  'zh-hant': '漢語',
  'zh-tw': '漢語',
  'zzzz': 'TEST-LANG'
};


// TBD: mo, nan-hant, nan-latn-pehoeji, nan-latn-tailo, nqo, nyn